--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/DaPigGuy/PiggyBackpacks
branches:
- master
projects:
  PiggyBackpacks:
    path: ""
    libs:
      - src: muqsit/InvMenu/InvMenu
        version: 2.1.0
...
